title: Fire Learn
description: Learning site for FIRE!
exclude: [README.md]
include: [".well-known"]

# applies pretty for all
permalink: pretty
plugins:
  - jekyll-relative-links

repository: LearningToBurn/ltb-theme@v2.0.2
remote_theme: LearningToBurn/ltb-theme@v2.0.2


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


collections:
  lessons:
    output: true
    sort_by: module_order